name: "Release version"

on: 
  push:
    tags:
    - 'v*.*.*'

env:
  EXT_GNAME: gitstash-*.vsix

jobs:
  release:
    name: Release version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create archive
        run: vsce package

      - name: GitHub Release
        id: step_3
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
          artifacts: $EXT_GNAME
          artifactContentType: application/zip
          draft: false
          prerelease: false
          artifactErrorsFailBuild: true
          generateReleaseNotes: false
